name: park_smart
description: A smart parking app that helps users find, reserve, and pay for parking spots.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_database: ^11.3.6
  
  # Authentication
  google_sign_in: ^6.3.0
  
  # Location
  geolocator: 14.0.0
  geocoding: ^3.0.0
  
  # Maps
  google_maps_flutter: ^2.4.0
  flutter_polyline_points: ^2.0.0
  
  # State Management
  provider: ^6.0.5
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  
  # Payments
  razorpay_flutter: ^1.4.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
