// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2vbHsCR0ePXTguedm6Vt0MGDttz7XZo',
    appId: '1:882355742482:web:df7e58317952b35a9c35cb',
    messagingSenderId: '882355742482',
    projectId: 'parksmart-a1f88',
    authDomain: 'parksmart-a1f88.firebaseapp.com',
    storageBucket: 'parksmart-a1f88.firebasestorage.app',
    measurementId: 'G-43M18N3837',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPiKQksLHkLmjf3lzysORF6eS6YirtFY',
    appId: '1:882355742482:android:f0a4ed1a61156bcb9c35cb',
    messagingSenderId: '882355742482',
    projectId: 'parksmart-a1f88',
    storageBucket: 'parksmart-a1f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGghQ6KI956Pg0Wjyn-e-n3XXXTdgk4eo',
    appId: '1:882355742482:ios:c9602c3c02e7830d9c35cb',
    messagingSenderId: '882355742482',
    projectId: 'parksmart-a1f88',
    storageBucket: 'parksmart-a1f88.firebasestorage.app',
    iosClientId: '882355742482-mb5ufuk59pifgmcmuvqh7ven89gprkk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.parksmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGghQ6KI956Pg0Wjyn-e-n3XXXTdgk4eo',
    appId: '1:882355742482:ios:c9602c3c02e7830d9c35cb',
    messagingSenderId: '882355742482',
    projectId: 'parksmart-a1f88',
    storageBucket: 'parksmart-a1f88.firebasestorage.app',
    iosClientId: '882355742482-mb5ufuk59pifgmcmuvqh7ven89gprkk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.parksmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR2vbHsCR0ePXTguedm6Vt0MGDttz7XZo',
    appId: '1:882355742482:web:e353224e2688c9f39c35cb',
    messagingSenderId: '882355742482',
    projectId: 'parksmart-a1f88',
    authDomain: 'parksmart-a1f88.firebaseapp.com',
    storageBucket: 'parksmart-a1f88.firebasestorage.app',
    measurementId: 'G-EL2GF0QL2C',
  );
}
